secrets use ENV

diff --git a/.github/workflows/release_build.yml b/.github/workflows/release_build.yml
--- a/.github/workflows/release_build.yml
+++ b/.github/workflows/release_build.yml
@@ -105,15 +105,15 @@ jobs:
       id-token: write
       contents: read
     steps:   
-      - name: Stop execution if secrets are missing
+      - name: Stop execution if secrets are missing or empty
         env:
           sentry_dsn: ${{ secrets.SENTRY_DSN }}
           firebase_app_check: ${{ secrets.FIREBASE_APP_CHECK }}
           firebase_vapid_key: ${{ secrets.FIREBASE_VAPID_KEY }}
-        if: ${{ env.sentry_dsn != null || env.firebase_app_check != null || env.firebase_vapid_key != null }}
+        if: ${{ env.sentry_dsn != null && env.sentry_dsn != '' && env.firebase_app_check != null && env.firebase_app_check != '' && env.firebase_vapid_key != null && env.firebase_vapid_key != '' }}
         run: |
-          echo "Required secrets are missing, stopping workflow."
-          exit 1 
+          echo "Required secrets are missing or empty, stopping workflow."
+          exit 1
 
       - name: Checkout
         uses: actions/checkout@v4.1.5
